{% set name = "s3contents" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfcf6c56d9758ee6503b7aff16a7ec39ce1f5bcd1f743755636924b0939c166e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  build:
    - hatch
  host:
    - python >=3
    - pip
    - hatch
  run:
    - python >=3
    - aiobotocore >=2.5.4
    - boto3
    - notebook
    - s3fs >=2021.0.0,<=2023.0.0
    - gcsfs >=2021.0.0,<=2023.0.0

test:
  requires:
    - mock
    - nose
    - pytest
  imports:
    - s3contents
    - s3contents.tests

about:
  home: https://github.com/danielfrg/s3contents
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A S3-backed ContentsManager implementation for Jupyter
  description: "A S3 and GCS backed ContentsManager implementation for Jupyter.\nIt aims to a be a transparent, drop-in replacement for Jupyter standard filesystem-backed storage system. With this implementation of a Jupyter Contents Manager you can save all your notebooks, regular files, directories structure directly to
    a S3/GCS bucket, this could be on AWS/GCP or a self hosted S3 API compatible like minio."
  dev_url: https://github.com/danielfrg/s3contents

extra:
  recipe-maintainers:
    - mariusvniekerk
    - danielfrg
