{% set name = "s3contents" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d612f650263a676ae01dd2fa9abb4d6f6d6e84e7c83c2188dc2808d36866e3be

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
  run:
    - python >=3
    - notebook
    - requests
    - boto3
    - s3fs >=0.3.4,<0.5.1
    - gcsfs >=0.2.1
    - nose

test:
  requires:
    - nose
    - mock
  imports:
    - s3contents
    - s3contents.tests

about:
  home: https://github.com/danielfrg/s3contents
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A S3-backed ContentsManager implementation for Jupyter
  description:

    A S3 and GCS backed ContentsManager implementation for Jupyter.

    It aims to a be a transparent, drop-in replacement for Jupyter standard
    filesystem-backed storage system. With this implementation of a Jupyter
    Contents Manager you can save all your notebooks, regular files, directories
    structure directly to a S3/GCS bucket, this could be on AWS/GCP or a self
    hosted S3 API compatible like minio.
  dev_url: https://github.com/danielfrg/s3contents

extra:
  recipe-maintainers:
    - mariusvniekerk
    - danielfrg
