{% set name = "s3contents" %}
{% set version = "0.4.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 648c956859d6d3a9a83d214b39654a490d34c8a3829d79c3ad316ef5fd8ba821

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jupyter
    - boto3
    - requests
    - s3fs
    - gcsfs

test:
  requires:
    - nose
    - mock
  imports:
    - s3contents
    - s3contents.tests

about:
  home: https://github.com/danielfrg/s3contents
  license: Apache 2.0
  license_family: APACHE
  license_file: 'LICENSE'
  summary: A S3-backed ContentsManager implementation for Jupyter
  description: |

    A S3 and GCS backed ContentsManager implementation for Jupyter.

    It aims to a be a transparent, drop-in replacement for Jupyter standard
    filesystem-backed storage system. With this implementation of a Jupyter
    Contents Manager you can save all your notebooks, regular files, directories
    structure directly to a S3/GCS bucket, this could be on AWS/GCP or a self
    hosted S3 API compatible like minio.
  dev_url: 'https://github.com/danielfrg/s3contents'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - danielfrg
