appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: i3Y27eRYgTSqHk2iAFBt1+KT2/WIULkkZd5itKiMWqOGeXC9JpYFDfmAZH3RGfdAZllp/kHMLh0o2YeQS/1T4WJ3w5RqiqNU7VPeipFNVK2lkfabb5wlM3L6JeAwqSqnjryKuTIMYGoNCtin4h25ozxqv0ZN22/wzbd/btWNNJ69xUkX7ADoOcR8cdipY6xBu+0mnZg6P/JMsPKsDKLkgvuczGAxIs1WMWpmvF0wYaUYqni5GrKa3HPOq5kaIdIVuCEAx6eoCKVJHHkMgALf6IaeDeBNczmup9oJNl7Mn1soLuK0xbMVs5zBcIqZg2HvO9ppY3RvMR8418Ks7+YbuXFHll/AHA2IrvX9txXnMwAusjKpTqJI56BPUzm2MElHsJPRFYYFQH5ZAQJ/QXXyzwhokOp/ffN0ordPEz9k9GzxhN3wdskkfvNhTOMaLA7o87eauwQQQ2nGlruI0T4sZ6nWilTlVF+ymfsgNpC2i2ZXAjUJP8gcWag2bKwUlvfYGwU4UBnZwMJ07fdbiapGHVmp36swO5zmw2XzJFVUoBhWhd3b5pz2zeShVcFqMYBNiVSAEcSsn2a3kVsNZGg7+BHrd7eySv2y7rzdjrBhYgbcN8KkI5pv4CaeL45DSaRgeGqWLnpF5aMutMz/7LFDss3z4gzYei4eVddnnbRHDbA=}
